name: Run Web Server Tests
on: [push]

defaults:
  run:
    working-directory: express

jobs:
  tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: docker build -t visulate-ora2pg:ci .
      - id: start_docker_container
        run: echo "::set-output name=container-id::$(docker run -d -p 3000:3000 -v "$(pwd)/ora2pg-projects":/project visulate-ora2pg:ci)"
      # - run: docker exec -it ${{ steps.start_docker_container.outputs.container-id }} bash
      # Install node dependencies
      - run: docker exec ${{ steps.start_docker_container.outputs.container-id }} ora2pg
      - run: docker exec ${{ steps.start_docker_container.outputs.container-id }} npm install
      # Run tests
      - run: docker exec ${{ steps.start_docker_container.outputs.container-id }} npm test
